name: Deploy

on:
    push:
      branches: [dev]
    pull_request:
      branches:
        - dev
       
jobs:
    deployer:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Deploy
          if: github.ref == 'refs/heads/feature/dev'
          env:
            DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          run: |
            curl "$DEPLOY_URL"